# Basic Information
title: Shi Chuan
position: Product Manager / AI Product Designer / Independent Developer
affiliation: Open to Opportunities
email: shic68748@gmail.com

# Profile
scholar_userid:
linkedin_userid:
github_userid: shic68748-gif

# Misc
favicon: "/assets/img/favicon.png"
canonical_url:

# Publication
scholar_googlescholar:
scholar_semanticscholar:

# Settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
timezone: Asia/Shanghai
